name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        recipes-version: [
          # save some cycles and infer it might
          # work on all versions between lowest and highest
          # "pangeo-forge-recipes==0.10.3",
          "pangeo-forge-recipes==0.10.4",
        ]
        beam-version: [
          "apache-beam==2.52.0",
        ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Setup minio + mc'
      run: |
        wget --quiet https://dl.min.io/server/minio/release/linux-amd64/minio
        chmod +x minio
        mv minio /usr/local/bin/minio

        wget --quiet https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        mv mc /usr/local/bin/mc

        minio --version
        mc --version

    - name: Install dependencies & our package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[test]"

    - name: Test with pytest
      run: |
        # setup
        # we need to make sure our matrix versions get added to target requirements.txt
        # so that the dynamic temp virtualenv stuff is targeting the correct version
        echo ${{ matrix.recipes-version }} >> tests/test-data/gpcp-from-gcs/feedstock-0.10.x/requirements.txt
        echo ${{ matrix.beam-version }} >> tests/test-data/gpcp-from-gcs/feedstock-0.10.x/requirements.txt
        # don't forget dictobj(s)
        echo ${{ matrix.recipes-version }} >> tests/test-data/gpcp-from-gcs/feedstock-0.10.x-dictobj/requirements.txt
        echo ${{ matrix.beam-version }} >> tests/test-data/gpcp-from-gcs/feedstock-0.10.x-dictobj/requirements.txt
        # kick it off
        pfrv=$(echo ${{ matrix.recipes-version }} | cut -d"=" -f3)
        pytest -vvv -s --cov=pangeo_forge_runner tests/unit/ --recipes-version=$pfrv

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
